# These are supported funding model platforms

github: [wahyu9kdl,awdev-corporation]
patreon: Awfanspage
open_collective: wahyu9kdl
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom:
  ["https://paypal.me/wahyudi9kdl","https://trakteer.id/awfanspage/tip","https://saweria.co/AwGroupChannel","https://sociabuzz.com/wahyu9kdl/donate"]
